global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        # prometheus
        - 'localhost:9090'
        # ruby-server
        - 'localhost:8000'
        # java-server
        - 'localhost:8001'
